FROM python:3

ENV PYTHONNUNBUFFERED 1
ENV PYTHONPATH "/equation-generator"

ENV DB_USER "root"
ENV DB_USER_PASSWORD "pass"
ENV HOST "172.17.0.3"
ENV PORT "3306"
ENV DATABASE "math"
ENV TABLE "equations"
ENV TIMER "10"
ENV MIN_COEFFICIENTS "4"
ENV MAX_COEFFICIENTS "10"
ENV MIN_COEFFICIENT_VALUE "1"
ENV MAX_COEFFICIENT_VALUE "30"
ENV MIN_COEFFICIENT_VALUE_SPECIAL "1"
ENV MAX_COEFFICIENT_VALUE_SPECIAL "10"
ENV MIN_EQUATIONS_IN_DB "10"
ENV EQUATIONS_TO_PUSH_IN_DB "1000"

RUN mkdir /equation-generator
WORKDIR /equation-generator
ADD . /equation-generator

RUN apt-get update
RUN pip install -r app/requirements.txt

CMD ["app/main.py"]
ENTRYPOINT ["python3"]
